ext {
    kafkaVersion = '4.2.0'
    slf4jVersion = '2.0.12'
    javaVersion = 21
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'application'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(rootProject.ext.javaVersion)
        }
    }

    tasks.withType(JavaCompile) {
        options.encoding = 'UTF-8'
    }

    repositories {
        mavenCentral()
    }

    dependencies {
        implementation "org.apache.kafka:kafka-clients:${rootProject.ext.kafkaVersion}"
        implementation "org.slf4j:slf4j-simple:${rootProject.ext.slf4jVersion}"
    }
}
