apply plugin: 'application'

application {
    mainClass = 'SimpleConsumer'
}

dependencies {
    implementation project(':common')
    implementation "org.apache.kafka:kafka-streams:${rootProject.ext.kafkaVersion}"
    implementation("tools.jackson.core:jackson-databind:3.1.0")
}

jar {
    manifest {
        attributes 'Main-Class': application.mainClass
    }
    archiveBaseName = 'kafka-consumer'
}