plugins {
    id 'java-library'
}

java {
    sourceCompatibility = project.rootProject.ext.javaVersion
    targetCompatibility = project.rootProject.ext.javaVersion
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.16.1'
    implementation "org.apache.kafka:kafka-clients:${project.rootProject.ext.kafkaVersion}"
}