apply plugin: 'application'

application {
    mainClass = 'SimpleProducer'
}

dependencies {
    implementation project(':common')
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.21.1'
}

jar {
    manifest {
        attributes 'Main-Class': application.mainClass
    }
    archiveBaseName = 'kafka-producer'
}